### ISSUE TITLE
Moveall compatible with current beets version?

### ISSUE THREAD

**Issue by taalas** [dsedivec/beets-plugins#3] opened 2015-06-16 09:55 UTC
Hi,

I am very interested in using your moveall plugin with my beets installation. After cloning your repo and using:

python setup.py build
python setup.py install

moveall throws an error when activated and invoked. Is moveall compatible with the current version? I can provide details if needed...

**Comment by dsedivec** [comment] 2015-06-21 02:53
Can you please provide the complete exception?  I'm unable to reproduce here.

**Comment by dsedivec** [comment] 2015-06-22 14:37
Sorry, I lied, I actually had a couple uncommitted changes, committed in c67038d91.  You can try the new HEAD now if you want.

**Comment by dsedivec** [comment] 2015-10-03 17:02
Closing this due to lack of feedback.  I just used these against Beets HEAD yesterday and they seemed to work.  Please re-open if you're still having problems.

**Closed by dsedivec** 2015-10-03 17:02 UTC
